### ISSUE TITLE
Missing resource mapping in netweaver config

### ISSUE THREAD

**Issue by marcelschork** [mauriciolauffer/ui5-deployer#19]
Hi @mauriciolauffer ,
thanks for the hint regarding #18 . The deployment was indeed successful, but I faced another issue 
```yaml
specVersion: '2.2'
metadata:
  name: ui5-showcase-app
type: application
customConfiguration:
  deployer:
    type: sap-netweaver
    sourcePath: dist/
    connection:
      url: https://sap.system.com
      strictSSL: false
    abapRepository:
      client: 100
      language: DE
      package: $TMP
      bspApplication: Z_UI5_SHOWCASE
      bspApplicationText: UI5 Showcase app
      appIndexCalculate: true
      skipAdtValidations: true
```
![deploy_error](https://user-images.githubusercontent.com/63337737/108813999-5e339780-75b2-11eb-862a-3d512e68549a.png)
The folder structure looks like follows

```
test
  -- dist
      -- Component-preload.js
      -- ...
  -- package.json
  -- ui5.yaml
```
The problem is the missing resource mapping in the yaml file
```yaml
resources:
  configuration:
    paths:
      webapp: dist
```
I guess the sample for SAP Netweaver needs an update here or should it work without explicit resource mapping?

Best regards,
Marcel

**Comment by mauriciolauffer** [comment]
Hi @marcelschork 
Could you share your project folder structure, please? Or, is it available in a public github repo which I could access and test on my side?

**Comment by marcelschork** [comment]
Hi @mauriciolauffer,
attached is a screenshot of the folder structure. I just used the openui5-sample-app, created a self-contained bundle and put it in a test folder together with package.json and ui5.yaml. The issue occurs if I omit the above mentioned resource mapping. Once I include it everything works fine.

<img width="870" alt="Screenshot 2021-02-24 at 20 30 15" src="https://user-images.githubusercontent.com/63337737/109055721-d6e44200-76df-11eb-8733-273408ce30d8.png">

**Comment by mauriciolauffer** [comment]
Hi @marcelschork 
You just need to change `sourcePath` to reflect your real folder structure. In this case, `sourcePath` would be `test/dist/` rather than `dist/`.
This should solve the problem.

**Comment by marcelschork** [comment]
Hi @mauriciolauffer, this does not solve the problem. The ui5.yaml is located inside the folder.
